### ISSUE TITLE
saving data to a database 

### ISSUE THREAD

**Issue by bilalh96** [vrdriver/Serial-PI-thon#1]
Hi there,
Nice code for a simple serial data reader. I wanted to ask whether you know how can I save this incoming data to a database. I want to store it in a CSV file and also save it to a database simultaneously. As I will be recording it for a longer period of time so just to be safe, want to add another method of saving it. 
would love to hear your thoughts on this :)

**Comment by vrdriver** [comment]
As for CSV, you'll have to investigate that one. 
However, for mysql and php, I'm using something like the following php code:
 

```
 
error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);
ini_set('display_errors',1);

	$hostname='localhost'; //// specify host, i.e. 'localhost'
	$user='username'; //// specify username
	$pass='password'; //// specify password
	$dbase='database'; //// specify database name	 
	$dbc = new mysqli($hostname, $user, $pass, $dbase);
	
if (mysqli_connect_errno())
  {
  echo "Failed to connect to MySQL: " . mysqli_connect_error();
  }
   
if (isset($_POST['column1'])) $column1 = addslashes(cleanQuery($_POST['column1'], $dbc));
if (isset($_POST['column2'])) $column2 = addslashes(cleanQuery($_POST['column2'], $dbc)); 
 
$query = "INSERT INTO table_name (column1, column2)
VALUES ('" . $column1 . "','" . $column2 . "')"; 
  
echo $query;  
 
$results = mysqli_query($dbc, $query);    
		
if ($results)
{ 
    echo "Log added.";
}
else
{
    echo "Update failed."; 
}

function cleanQuery($string, $dbc)
// This is aimed to prevent XSS and SQL injection, and extra conversions to the text if required.
{ 
 
  if(get_magic_quotes_gpc())  // prevents duplicate backslashes
  {
    $string = stripslashes(trim($string));
  }
  if (phpversion() >= '4.3.0')
  {
    $string = mysqli_real_escape_string($dbc,trim($string));
  }
  else
  {
    $string = mysqli_escape_string($dbc,trim($string));
  } 
  return $string;
}

```
For this example to work, you'll need to create a table in mysql and and give it 2 columns.
In this case, for the example: table_name, will have column1 and column2.

**Comment by bilalh96** [comment]
Hi Steve,

Thanks for providing a basic eg for it . regarding your serial code , I
wanted to ask you have used flush input which I believe is to clear input
buffer before reading anything which is now replaced for
reset_input_buffer() in new pyserial version. However, why dont you
close the serial port and use reset_output_buffer too just so that next
time code runs it should start fresh.
The reason for me asking you this is because I faced " ,* ' File
"C:\Users\XXX\Anaconda3\envs\py36\lib\site-packages\serial\serialwin32.py",
line 62, in open raise SerialException("could not open port {!r}:
{!r}".format(self.portstr, ctypes.WinError())) SerialException: could not
open port 'COM3': PermissionError(13, 'Access is denied.', None, 5) " *

When I went over StackOverflow, people suggested there to use ser.close()
too . Just wanted to know your thoughts on this as I wasnt able to run the
code multiple times since it seemed that my USB - TTL adapter had a COM
port already in use which I couldn't figure out how and where. Let me know
what you think

kind regards,
Bilal

**Comment by vrdriver** [comment]
I have no idea. maybe you are trying to use the wrong com port or wrong baud rate... ?
I'm not a python expert unfortunately. I just got lucky with this which worked for me... :/
If I recall, mine doesn't clear a buffer, as it separates the text when a new line arrives, as per line 25, and then at 29.

**Comment by bilalh96** [comment]
no, everything is fine. I have read that before too baud rate and coms is
fine. can I know did you write this code on your own or any source that you
followed while creating it.
btw line 13 is what I am talking about. this is supposed to clear the input
buffer register.

**Comment by vrdriver** [comment]
I can't remember which example I followed. It was a long time ago. But, there heaps of examples out there. I may have even used my python book. To me, it looks like line 13 just resets the buffer, to make it ready for reading the usb terminal.

**Comment by bilalh96** [comment]
Thanks, I'll check it out. btw can I know in line 28 you mentioned open a
csv file in append mode with 'f' , what does this 'f' means here?

**Comment by vrdriver** [comment]
Read the comments down further on lines 33-35.
The f gives python a way to interact with the file for writing.
The f is a variable that has all of the methods for a file you want to use.
See the help documentation here: https://docs.python.org/3/tutorial/inputoutput.html.  At section 7.2
